### ISSUE TITLE
Clarify how to run this sample

### ISSUE THREAD

**Issue by SeanFeldman** [Azure-Samples/monitor-dotnet-metrics-api#4]
In the steps how to run the sample, [step 4 uses `export` command](https://github.com/Azure-Samples/monitor-dotnet-metrics-api#run-this-sample).

It does not appear to be a `dotnet` option. What is it?

**Comment by SeanFeldman** [comment]
Also, this project needs to be converted from .projx to a standard .csproj or .sln + project file.

**Comment by mikegoatly** [comment]
For anyone still interested, `export` is a linux command that sets an environment variable. The sample currently reads the configuration from environment variables why is why the instructions are getting you to do that.

From a command prompt on Windows you'd need to use:
``` cmd
SET AZURE_TENANT_ID={your tenant id}
SET AZURE_CLIENT_ID={your client id}
SET AZURE_CLIENT_SECRET={your client secret}
SET AZURE_SUBSCRIPTION_ID={your subscription id}
```

Or if you're using Powershell:
``` powershell
$env:SET AZURE_TENANT_ID="{your tenant id}"
$env:AZURE_CLIENT_ID="{your client id}"
$env:AZURE_CLIENT_SECRET="{your client secret}"
$env:AZURE_SUBSCRIPTION_ID="{your subscription id}"
```

Before executing the `dotnet run` command.

**Comment by SeanFeldman** [comment]
Kind of sad that after 2 years no one has even looked at this issue.
